base: &base
  amazon: {
    s3_bucket: fake,
    access_key_id: fake,
    secret_access_key: fake
  }

development:
  <<: *base
  
test:
  <<: *base 

production:
  amazon: {
    s3_bucket: ENV['S3_BUCKET_NAME'],
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  }
